- name: Base setup
  hosts: all
  become: true
  roles:
    - base

- name: Install application dependencies
  hosts: webservers
  become: true
  roles:
    - node

- name: Deploy application
  hosts: webservers
  roles:
    - deploy

- name: Install and configure nginx
  hosts: webservers
  become: true
  roles:
    - nginx
